# Generated by Django 4.2.5 on 2023-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langchainattr',
            name='assignments',
            field=models.TextField(default=''),
        ),
    ]
