# Generated by Django 4.2.5 on 2023-10-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchainapp", "0002_langchainattr_assignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("write", models.TextField()),
                ("user_id", models.IntegerField()),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "write_store",
            },
        ),
    ]
