# Generated by Django 4.2.5 on 2023-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchainapp", "0003_writestore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writestore",
            name="user_id",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
